//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  5 2019 01:19:34).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@protocol DVTFileSystemRepresentationProviding
- (void)dvt_provideFileSystemRepresentationToBlock:(void (^)(char *, unsigned long long))arg1;
@end

