os: osx
language: objective-c
xcode_project: xcnew.xcodeproj
xcode_scheme: xcnew

matrix:
  include:
  - osx_image: xcode10.2
  - osx_image: xcode10.1

script:
  - |
    make check
    make install
    make uninstall
