#!/bin/sh

is_developer_dir_in_xcode() {
    bundle_id="$(/usr/libexec/PlistBuddy -c 'Print :CFBundleIdentifier' "${1}/../Info.plist" 2>/dev/null)"
    test "$bundle_id" = 'com.apple.dt.Xcode'
}

get_rpaths() {
    xcrun otool -l "$1" | sed -ne '/cmd LC_RPATH/,/path /s/^ *path \(.*\) (offset [0-9]*)$/\1/p'
}

developer_dir="$(xcode-select --print-path)"
if ! is_developer_dir_in_xcode "$developer_dir"; then
    exit 1
fi

for old_rpath in $(get_rpaths "${INSTALLER_PAYLOAD_DIR}/usr/local/bin/xcnew")
do
    new_rpath="$(echo "$old_rpath" | sed -e "s|.*/Contents/Developer|$developer_dir|")"
    install_name_tool -rpath "$old_rpath" "$new_rpath" "${INSTALLER_PAYLOAD_DIR}/usr/local/bin/xcnew"
done
