//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  5 2019 01:19:34).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@import Foundation.NSObject;

@class IDETemplateOption, IDEWorkspace, NSString;

@protocol IDETemplateOptionParent <NSObject>
@property(retain, nonatomic) IDEWorkspace *workspace;
@property(readonly, copy) NSString *identifier;
- (void)valueDidChangeForOption:(IDETemplateOption *)arg1;
@end

