#!/bin/bash

set -ex

tempdir="$(mktemp -d)"
trap "rm -Rf '$tempdir'" EXIT

dstroot="${tempdir}/dstroot"
mkdir "$dstroot"

version="$(agvtool vers -terse)"

xcodebuild install -project xcnew.xcodeproj -scheme xcnew -configuration Release -quiet BUILD_DIR="${tempdir}/build" DSTROOT="$dstroot" INSTALL_PATH='/usr/local/bin'

pkgbuild \
    --root "$dstroot" \
    --identifier com.github.manicmaniac.xcnew \
    --version "$version" \
    --ownership recommended \
    --scripts Package/Scripts \
    "${tempdir}/xcnew.pkg"
trap "rm -f '${tempdir}/xcnew.pkg'" EXIT

old_wd="$PWD"
(
    cd "$tempdir"
    productbuild \
        --distribution "${old_wd}/Package/Distribution.xml" \
        --resources "${old_wd}/Package/Resources" \
        "${old_wd}/xcnew-${version}.pkg"
)
