#!/bin/bash

set -ex

destdir="$(mktemp -d)"
trap "rm -Rf '$destdir'" EXIT

version="$(agvtool vers -terse)"

xcodebuild install -project xcnew.xcodeproj -scheme xcnew -configuration Release -quiet DSTROOT="$destdir" INSTALL_PATH='/usr/local/bin'

pkgbuild \
    --root "$destdir" \
    --identifier com.github.manicmaniac.xcnew \
    --version "$version" \
    --ownership recommended \
    --scripts Package/Scripts \
    xcnew.pkg
trap 'rm -f xcnew.pkg' EXIT

productbuild \
    --distribution Package/Distribution.xml \
    "xcnew-${version}.pkg"
