#!/bin/sh

# A utility script to dump Xcode private headers that are used in `xcnew`.
#
# This tool needs the following commands to be installed:
# See `Frameworks/.versions` to know which version of the tools are needed.
#
# - [Xcode](https://developer.apple.com/download/all/)
# - [clang-format](https://clang.llvm.org/docs/ClangFormat.html)
# - [class-dump](http://github.com/manicmaniac/class-dump)

set -e

contents_dir="$(dirname "${DEVELOPER_DIR:-$(xcode-select -p)}")"

tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT

# Dump necessary headers in DVTFoundation.framework.
ktool dump --headers --out "$tmpdir" "$contents_dir/SharedFrameworks/DVTFoundation.framework/DVTFoundation"
mv "$tmpdir/DVTExtension.h" \
    "$tmpdir/DVTFilePath.h" \
    "$tmpdir/DVTFileSystemRepresentationProviding-Protocol.h" \
    "$tmpdir/DVTPlatform.h" \
    "$tmpdir/DVTPropertyListEncoding-Protocol.h" \
    Frameworks/DVTFoundation.framework/Headers

# Dump necessary headers in IDEFoundation.framework.
ktool dump --headers --out "$tmpdir" "$contents_dir/Frameworks/IDEFoundation.framework/IDEFoundation"
mv "$tmpdir/IDETemplate.h" \
    "$tmpdir/IDETemplateFactory.h" \
    "$tmpdir/IDETemplateInstantiationContext.h" \
    "$tmpdir/IDETemplateKind.h" \
    "$tmpdir/IDETemplateOption.h" \
    "$tmpdir/IDETemplateOptionParent-Protocol.h" \
    Frameworks/IDEFoundation.framework/Headers

find Frameworks -type f -name '*.h' -exec sed -i '' -E -f /dev/fd/0 {} + <<-'EOF'
    # Remove C++ destructor declaration, which is not permitted in Objective-C class.
    /^- (id)\.cxx_destruct;$/d

    # Import Foundation.framework instead of importing individual headers.
    /^#import "NS.*$/d

    # Use `NSUInteger` instead of an architecture-dependent type `unsigned long long`.
    s/unsigned long long hash;$/NSUInteger hash;/

    # Add an explicit ownership to avoid warnings.
    # s/(id \*_field2;)$/__unsafe_unretained \1/

    # Remove all instance variables.
    / *{/,/}/{
        s/(.*) *{/\1/g
        t
        d
    }

    # Use forward declarations
    s/^#import "(DVT|IDE)([^.-]*)\.h"/@class \1\2;/g

    # Remove import statements for Swift types
    /^#import "_.*\.h"/d

    # Remove Swift type references
    /^@property.*\) _.*;$/d

    # Workaround for possible ktool's bug
    s/\(\*unk/(void */g
    s/\(\*([A-Za-z0-9]+)/(\1 */g
    s/^#import "IDEProvisioningBasicTeam-Protocol.h"$/@protocol IDEProvisioningBasicTeam;/g

    # Fix warning: type of property 'workspace' does not match type of accessor 'setWorkspace:'
    /^-.*setWorkspace:\(id\).*$/d

    # Fix warning: no 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed [-Wobjc-property-no-attribute]
    s/^@property *NSObject<([^ >]+)> *\*([A-Za-z1-9_]+);/@property(retain) id<\1> \2;/g

    # Fix error: property with 'copy' attribute must be of object type
    s/@property *\(copy\) *id \*templateFilter;/@property (copy) id templateFilter;/g
EOF

# Re-format all files.
find Frameworks -type f -name '*.h' -exec clang-format -i {} +

# Dump .tbd files
xcrun tapi installapi \
    -target x86_64-apple-macosx \
    -target arm64-apple-macosx \
    -install_name '@rpath/DVTFoundation.framework/Versions/A/DVTFoundation' \
    -F Frameworks \
    -extra-public-header Frameworks/DVTFoundation.framework/Headers \
    -o Frameworks/DVTFoundation.framework/DVTFoundation.tbd \
    "$contents_dir/SharedFrameworks/DVTFoundation.framework"

xcrun tapi installapi \
    -target x86_64-apple-macosx \
    -target arm64-apple-macosx \
    -install_name '@rpath/IDEFoundation.framework/Versions/A/IDEFoundation' \
    -F Frameworks \
    -extra-public-header Frameworks/IDEFoundation.framework/Headers \
    -o Frameworks/IDEFoundation.framework/IDEFoundation.tbd \
    "$contents_dir/Frameworks/IDEFoundation.framework"

# Sometimes tapi installapi leaves whitespaces at the end of line.
find Frameworks -type f -name '*.tbd' -exec sed -i '' -e 's/ *$//g' {} +

# To reproduce the result, tool versions are recorded.
(
    exec 2>&1
    set -x
    xcodebuild -version
    ktool -V
    clang-format --version
) >Frameworks/.versions
