#!/bin/sh

# A utility script to dump Xcode private headers that are used in `xcnew`.
#
# This tool needs the following commands to be installed:
# See `Frameworks/.versions` to know which version of the tools are needed.
#
# - [Xcode](https://developer.apple.com/download/all/)
# - [clang-format](https://clang.llvm.org/docs/ClangFormat.html)
# - [class-dump](http://github.com/manicmaniac/class-dump)

set -e

contents_dir="$(dirname "${DEVELOPER_DIR:-$(xcode-select -p)}")"

# Dump necessary headers in DVTFoundation.framework.
class-dump -H \
           -C '^DVT(FilePath|FileSystemRepresentationProviding|Platform)$' \
           -o Frameworks/DVTFoundation.framework/Headers \
           "$contents_dir/SharedFrameworks/DVTFoundation.framework"

# Dump necessary headers in IDEFoundation.framework.
class-dump -H \
           -C '^IDETemplate(|Factory|InstantiationContext|Kind|Option|OptionParent)$' \
           -o Frameworks/IDEFoundation.framework/Headers \
           "$contents_dir/Frameworks/IDEFoundation.framework"

find Frameworks -type f -name '*.h' -exec sed -i '' -f /dev/fd/0 {} + <<-'EOF'
    # Import Foundation.framework instead of importing individual headers.
    s/^#import <objc\/NSObject\.h>$/#import <Foundation\/Foundation.h>/
    /^#import "NS.*$/d

    # Use `NSUInteger` instead of an architecture-dependent type `unsigned long long`.
    s/unsigned long long hash;$/NSUInteger hash;/

    # Add an explicit ownership to avoid warnings.
    s/\(id \*_field2;\)$/__unsafe_unretained \1/

    # Remove all instance variables.
    / *{/,/}/d

    # Workaround for a bug in class-dump 3.5-0.1.1 running on arm64
    s/_Bool/BOOL/g
EOF

# CDStructure.h is not used.
rm Frameworks/DVTFoundation.framework/Headers/CDStructures.h Frameworks/IDEFoundation.framework/Headers/CDStructures.h

# Re-format all files.
find Frameworks -type f -name '*.h' -exec clang-format -i {} +

# Dump .tbd files
xcrun tapi installapi \
    -target x86_64-apple-macosx \
    -target arm64-apple-macosx \
    -install_name '@rpath/DVTFoundation.framework/Versions/A/DVTFoundation' \
    -F Frameworks \
    -extra-public-header Frameworks/DVTFoundation.framework/Headers \
    -o Frameworks/DVTFoundation.framework/DVTFoundation.tbd \
    "$contents_dir/SharedFrameworks/DVTFoundation.framework"

xcrun tapi installapi \
    -target x86_64-apple-macosx \
    -target arm64-apple-macosx \
    -install_name '@rpath/IDEFoundation.framework/Versions/A/IDEFoundation' \
    -F Frameworks \
    -extra-public-header Frameworks/IDEFoundation.framework/Headers \
    -o Frameworks/IDEFoundation.framework/IDEFoundation.tbd \
    "$contents_dir/Frameworks/IDEFoundation.framework"

# Sometimes tapi installapi leaves whitespaces at the end of line.
find Frameworks -type f -name '*.tbd' -exec sed -i '' -e 's/ *$//g' {} +

# To reproduce the result, tool versions are recorded.
(
    exec 2>&1
    set -x
    xcodebuild -version
    class-dump --version
    clang-format --version
) >Frameworks/.versions
