#!/usr/bin/env python3

from distutils.util import strtobool
import json
import os
import re
import sys
from urllib.parse import quote, unquote


class Workflow(object):
    _xcodes_re = re.compile(r'xcode: (\[.*\])$')
    _indent_re = re.compile(r'^( *)')

    def __init__(self, f):
        """
        >>> import io
        >>> f = io.StringIO(_test_yaml)
        >>> workflow = Workflow(f)
        >>> workflow.xcodes
        ['13.4.1', '13.3.1']
        >>> workflow.includes
        []
        """
        self.xcodes = []
        self.includes = []
        for line in f:
            matched = self._xcodes_re.search(line)
            if matched:
                self.xcodes = json.loads(matched.group(1))
        f.seek(0)
        self.contents = f.read()

    def __str__(self):
        """
        >>> import io
        >>> f = io.StringIO(_test_yaml)
        >>> workflow = Workflow(f)
        >>> str(workflow) == _test_yaml
        True
        >>> workflow.includes.append(('macOS-12', '14'))
        >>> str(workflow) == _test_yaml
        False
        """
        lines = []
        for line in self.contents.splitlines(keepends=True):
            matched = self._xcodes_re.search(line)
            if matched:
                indent = self._indent_re.match(line).group(1)
                lines.append(f'{indent}xcode: {json.dumps(self.xcodes)}\n')
                continue
            if 'include:' in line:
                lines.append(line)
                indent = self._indent_re.match(line).group(1)
                for macos, xcode in self.includes:
                    lines.append(f'{indent}- macos: {macos}\n')
                    lines.append(f'{indent}  xcode: "{xcode}"\n')
                continue
            lines.append(line)
        return ''.join(lines)


class Readme(object):
    _badge_re = re.compile(r'xcode-(.*)-blue')
    _max_xcode_version_re = re.compile(r'Xcode <= (\d+(\.\d+){0,2})')

    def __init__(self, f):
        """
        >>> import io
        >>> f = io.StringIO(_test_readme)
        >>> readme = Readme(f)
        >>> readme.contents == _test_readme
        True
        >>> sorted(readme.badge_versions)
        ['12', '13']
        >>> readme.max_xcode_version
        '13.4.1'
        """
        for line in f:
            matched = self._badge_re.search(line)
            if matched:
                captured = matched.group(1)
                self.badge_versions = set(unquote(captured).split(' | '))
            matched = self._max_xcode_version_re.search(line)
            if matched:
                self.max_xcode_version = matched.group(1)
                break
        else:
            raise RuntimeError(f'Does not contain Xcode version string')
        f.seek(0)
        self.contents = f.read()

    def __str__(self):
        """
        >>> import io
        >>> f = io.StringIO(_test_readme)
        >>> readme = Readme(f)
        >>> str(readme) == _test_readme
        True
        >>> readme.max_xcode_version = '14'
        >>> str(readme) == _test_readme
        False
        """
        contents = self._max_xcode_version_re.sub(
                f'Xcode <= {self.max_xcode_version}', self.contents)
        quoted_versions = quote(' | ').join(sorted(self.badge_versions))
        contents = self._badge_re.sub(
                f'xcode-{quoted_versions}-blue', contents)
        return contents


def _main(argv=sys.argv):
    if strtobool(os.getenv('DOCTEST', '0')):
        import doctest
        return doctest.testmod()
    if len(argv) != 3:
        print(f'usage: {argv[0]} <XCODE_VERSION> <RUNNER>')
    current_xcode_version = argv[1]
    runner = argv[2]
    workflow_path = '.github/workflows/test.yml'
    readme_path = 'README.md'

    with open(workflow_path) as f:
        workflow = Workflow(f)
    if current_xcode_version in workflow.xcodes:
        sys.exit(1)
    workflow.xcodes.insert(0, current_xcode_version)
    workflow.includes.insert(0, (runner, current_xcode_version))
    with open(workflow_path, 'w') as f:
        f.write(str(workflow))

    with open(readme_path) as f:
        readme = Readme(f)
    readme.badge_versions.add(current_xcode_version.split('.')[0])
    readme.max_xcode_version = current_xcode_version
    with open(readme_path, 'w') as f:
        f.write(str(readme))


_test_yaml = '''
name: test
on: push
jobs:
  test:
    runs-on: ${{ matrix.macos }}
    strategy:
      matrix:
        xcode: ["13.4.1", "13.3.1"]
        include:
        - macos: macOS-12
          xcode: "13.4.1"
        - macos: macOS-12
          xcode: "13.3.1"
    steps:
    - uses: actions/checkout@v3
'''

_test_readme = '''
[![Xcode](https://img.shields.io/badge/xcode-12%20%7C%2013-blue)](https://github.com/manicmaniac/xcnew#supported-xcode-versions)
`Xcode >= 12.5 && Xcode <= 13.4.1`.
'''


if __name__ == '__main__':
    _main()
