#!/usr/bin/env python3

"""
A script to update <docdate> in manpages.
"""

from argparse import ArgumentParser
import datetime as dt
from distutils.util import strtobool
import fileinput
import os
import re
import sys


_docdate_line_re = re.compile(
    r'^(?P<prefix>\s*<docdate>).*(?P<suffix></docdate>\s*)$')


def substitute_docdate(new_docdate, lines):
    """
    >>> lines = ['<docdate>Septempber 28, 2021</docdate>']
    >>> for line in substitute_docdate('September 29, 2021', lines):
    ...     print(line)
    <docdate>September 29, 2021</docdate>
    """
    replacement = r'\g<prefix>{0}\g<suffix>'.format(new_docdate)
    for line in lines:
        yield _docdate_line_re.sub(replacement, line)


def format_date(date):
    """
    >>> date = dt.date(2021, 9, 2)
    >>> print(format_date(date))
    September 2, 2021
    """
    return date.strftime('%B {0}, %Y').format(date.day)


def _main(argv=sys.argv):
    if strtobool(os.getenv('DOCTEST', '0')):
        import doctest
        return doctest.testmod()
    today = format_date(dt.date.today())
    parser = ArgumentParser(description=__doc__)
    parser.add_argument('-d', '--date', default=today,
                        help='new date (default: {0})'.format(today))
    parser.add_argument('-i', '--inplace', action='store_true',
                        help='edit files in-place')
    parser.add_argument('files', nargs='+', metavar='FILE',
                        help='path to files to edit')
    args = parser.parse_args(argv[1:])
    file_input = fileinput.input(files=args.files, inplace=args.inplace)
    for line in substitute_docdate(args.date, file_input):
        sys.stdout.write(line)


if __name__ == '__main__':
    _main()
