name: Package
on:
  push:
    tags:
    - '*.*.*'
jobs:
  package:
    runs-on: macOS-12
    defaults:
      run:
        shell: bash
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.4.1.app/Contents/Developer
    steps:
    - uses: actions/checkout@v3
    - run: make xcnew.pkg
    - name: Install package
      run: sudo installer -pkg xcnew.pkg -target /
    - name: Test installed package
      run: make installcheck | xcpretty
    - run: man -P cat 1 xcnew
    - name: Create release
      run: gh release create '${{ github.ref }}' --generate-notes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload release asset
      run: gh release upload '${{ github.ref }}' xcnew.pkg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
