name: Test
on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: macOS-13
    defaults:
      run:
        shell: bash
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.3.app/Contents/Developer
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install Python dependencies
      run: pip install -r requirements.txt
    - name: Install dependencies
      run: brew install clang-format
    - name: Dump private headers
      run: Scripts/generate-framework-stubs
    - name: Show diff
      run: git diff
