name: Test
on: [push]
jobs:
  unit-test:
    runs-on: macOS-10.15
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        xcode: ["12.4", "12", "11.7", "11.2.1"]
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        run: make check | xcpretty
      - name: Install
        run: make install | xcpretty
