name: Test
on: [push]
jobs:
  unit-test:
    runs-on: ${{ matrix.macos }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        xcode: ["13.3.1", "13.2.1", "13.1", "13.0", "12.5"]
        include:
        - macos: macOS-12
          xcode: "13.3.1"
        - macos: macOS-11
          xcode: "13.2.1"
        - macos: macOS-11
          xcode: "13.1"
        - macos: macOS-11
          xcode: "13.0"
        - macos: macOS-11
          xcode: "12.5"
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run unit tests
        run: make check | xcpretty
      - name: Install
        run: make install | xcpretty
