name: Update Xcode
on: workflow_dispatch
jobs:
  update-xcode:
    runs-on: macOS-13
    steps:
    - uses: actions/checkout@v3
    - uses: maxim-lobanov/setup-xcode@v1
      id: setup-xcode
      with:
        xcode-version: latest-stable
    - name: Configure Git
      run: |
        git config --local user.email 'github-actions[bot]@users.noreply.github.com'
        git config --local user.name 'github-actions[bot]'
        git checkout -b support-xcode-${{ steps.setup-xcode.outputs.version }}
    - name: Update Xcode
      id: update-xcode
      run: Scripts/update-xcode ${{ steps.setup-xcode.outputs.version }} macOS-13
    - name: Commit Xcode update
      run: |
        git commit --all --file=- <<-EOF
        Add Xcode ${{ steps.setup-xcode.outputs.version }} to test targets

        ./Scripts/update-xcode ${{ steps.setup-xcode.outputs.version }} macOS-13
        EOF
    - name: Install Homebrew dependencies
      run: brew install clang-format
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install Python dependencies
      run: pip install -r requirements.txt
    - name: Dump private headers
      continue-on-error: true
      run: Scripts/generate-framework-stubs
    - name: Commit private headers
      run: |
        git commit --all --file=- <<-EOF
        Dump private headers with Xcode ${{ steps.setup-xcode.outputs.version }}

        ./Scripts/generate-framework-stubs
        EOF
    - name: Create pull request
      run: |
        git push --set-upstream origin support-xcode-${{ steps.setup-xcode.outputs.version }}
        gh pr create --title 'Support Xcode ${{ steps.setup-xcode-outputs.version }}' --body-file - <<-EOF
        Add Xcode ${{ steps.setup-xcode.outputs.version }} to test targets.

        See https://developer.apple.com/documentation/xcode-release-notes for Xcode release notes.

        This pull request is created by [`${{ github.workflow }}` workflow](https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/.github/workflows/update-xcode.yml).
        EOF
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
