name: Update Xcode
on: workflow_dispatch
jobs:
  update-xcode:
    runs-on: macOS-12
    steps:
    - uses: actions/checkout@v3
    - name: Configure Git
      run: |
        git config --local user.email 'github-actions[bot]@users.noreply.github.com'
        git config --local user.name 'github-actions[bot]'
    - uses: maxim-lobanov/setup-xcode@v1
      id: setup-xcode
      with:
        xcode-version: latest-stable
    - name: Update Xcode
      id: update-xcode
      continue-on-error: true
      run: Scripts/update-xcode ${{ steps.setup-xcode.outputs.version }} macOS-12
    - name: Commit Xcode update
      if: ${{ steps.update-xcode.outcome == 'success' }}
      run: |
        git commit --all --file=- <<-EOF
        Add Xcode ${{ steps.setup-xcode.outputs.version }} to test targets

        ./Scripts/update-xcode ${{ steps.setup-xcode.outputs.version }} macOS-12
        EOF
    - name: Install dependencies
      run: brew install clang-format manicmaniac/tap/class-dump
      if: ${{ steps.update-xcode.outcome == 'success' }}
    - name: Dump private headers
      if: ${{ steps.update-xcode.outcome == 'success' }}
      run: Scripts/dump-private-headers
    - name: Commit private headers
      if: ${{ steps.update-xcode.outcome == 'success' }}
      run: |
        git commit --all --file=- <<-EOF
        Dump private headers with Xcode ${{ steps.setup-xcode.outputs.version }}

        ./Scripts/dump-private-headers
        EOF
    - uses: peter-evans/create-pull-request@v4
      if: ${{ steps.update-xcode.outcome == 'success' }}
      with:
        title: Support Xcode ${{ steps.setup-xcode.outputs.version }}
        body: |
          Add Xcode ${{ steps.setup-xcode.outputs.version }} to test targets.

          See https://developer.apple.com/documentation/xcode-release-notes for Xcode release notes.

          This pull request is created by [`${{ github.workflow }}` workflow](https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/.github/workflows/update-xcode.yml).
        branch: support-xcode-${{ steps.setup-xcode.outputs.version }}
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
