name: CI
on: push
jobs:
  unit-test:
    runs-on: macOS-10.14
    strategy:
      fail-fast: false
      matrix:
        xcode: ["11", "10.3", "10.2.1", "10.1"]
    steps:
      - uses: actions/checkout@v1
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      - name: Run unit tests
        run: set -o pipefail && xcodebuild test -project xcnew.xcodeproj -scheme xcnew | xcpretty
      - name: Run install tests
        run: set -o pipefail && make install | xcpretty
